config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'core#index'
  resources :core, only: :index
  resources :orders
  resources :ingredients, except: %i[index show]
  resources :dishes
  resources :clients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  has_and_belongs_to_many :orders, dependent: :destroy
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_and_belongs_to_many :ingredients, dependent: :destroy
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_and_belongs_to_many :dishes, dependent: :destroy
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :dish
  has_and_belongs_to_many :clients, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  def index; end

  def edit; end

  def update; end

  def new; end

  def create; end

  def show; end

  def destroy; end
end

app/controllers/core_controller.rb
# frozen_string_literal: true

class CoreController < ApplicationController
  def index; end
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

class DishesController < ApplicationController
  # GET /dishes
  def index
    @dishes = Dish.all
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    new_params = dish_params.reject { |c, _v| c == "ingredient_id" }
    @dish = Dish.find(params[:id])
    @ingredient_id = dish_params["ingredient_id"]
    @ingredient = Ingredient.find(@ingredient_id)
    @dish.ingredients << @ingredient
    if @dish.update(new_params)
      redirect_to dishes_path @dish
    else
      render 'edit'
    end
  end

  def new
    @dish = Dish.new
  end

  def create
    new_params = dish_params.reject { |c, _v| c == "ingredient_id" }
    @dish = Dish.new(new_params)   
    @ingredient_id = dish_params["ingredient_id"]
    @ingredient = Ingredient.find(@ingredient_id)
    @dish.ingredients << @ingredient
    if @dish.save
      redirect_to dishes_path @dish
    else
      render 'new'
    end
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    redirect_to dishes_path
  end

  private

  def dish_params
    params.require(:dish).permit( :name, :price, ingredient_id: [] )
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to root_path @ingredient
    else
      render 'edit'
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to root_path @ingredient
    else
      render 'new'
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to root_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to root_path @order
    else
      render 'edit'
    end
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to root_path @order
    else
      render 'new'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:room, :table, :dish_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clients_helper.rb
# frozen_string_literal: true

module ClientsHelper
end

app/helpers/core_helper.rb
# frozen_string_literal: true

module CoreHelper
end

app/helpers/dishes_helper.rb
# frozen_string_literal: true

module DishesHelper
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<h1>Clients#edit</h1>
<p>Find me in app/views/clients/edit.html.erb</p>

app/views/clients/index.html.erb
<h1>Clients#index</h1>
<p>Find me in app/views/clients/index.html.erb</p>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/core/index.html.erb
<h1>Las Palmeritas Restaurant</h1>
<h2>Pedido</h2>
<%= link_to  "Hacer un Pedido", orders_path %>
<h2>Platos</h2>
<%= link_to  "Ver la carta", dishes_path %>
<h2>Ventas</h2>
<p>Estadisticas de las ventas</p>

app/views/dishes/_form.html.erb
<%=form_with model: @dish, local: true do |form| %>
  <div class = "form-erros">
    <% if @dish.errors.any? %>
    <ul>
      <% @dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :ingredient_id %>
    <%= form.collection_select :ingredient_id, Ingredient.all, :id, :name, { selected: @ingredient_id, include_hidden: false }, {:multiple => true} %>
  </div>

  <div>
    <%= link_to  "Nuevo ingrediente", new_ingredient_path %>
  </div>

  <div>
    <%= form. submit %> 
  </div>
<% end %>

app/views/dishes/create.html.erb
<h1>Dishes#create</h1>
<p>Find me in app/views/dishes/create.html.erb</p>

app/views/dishes/destroy.html.erb
<h1>Dishes#destroy</h1>
<p>Find me in app/views/dishes/destroy.html.erb</p>

app/views/dishes/edit.html.erb
<h1>Editar plato</h1>
<%= render 'form' %>
<%= link_to  "Atras", dishes_path %>

app/views/dishes/index.html.erb
<h1>Menu</h1>
<h2>Lista de todos los platos</h2>
<%= link_to  "Nuevo plato", new_dish_path %>
<%= link_to  "Atras", root_path %>
<% @dishes.each do |dish| %>
<p><%= link_to  dish.name, dish_path(dish) %></p>
<p>Precio: <%= dish.price %></p>
<%= link_to  "Editar", edit_dish_path(dish) %>
<%= link_to "Borrar", dish_path(dish), method: :delete, data:{confirm:"Are you sure?"}%>
<% end %>

app/views/dishes/new.html.erb
<h1>Nuevo Plato</h1>
<%= render 'form' %>
<%= link_to  "Atras", dishes_path %>

app/views/dishes/show.html.erb
<h2><%= @dish.name %></h2>
<p>Ingredientes:</p>
<ul>
<% @dish.ingredients.each do |ingredient| %>
 <li><%= ingredient.name %></li>
 <% end %>
</ul>
<%= link_to  "Atras", dishes_path %>

app/views/dishes/update.html.erb
<h1>Dishes#update</h1>
<p>Find me in app/views/dishes/update.html.erb</p>

app/views/ingredients/_form.html.erb
<%=form_with model: @ingredient, local: true do |form| %>
  <div class = "form-erros">
    <% if @ingredient.errors.any? %>
    <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form. submit %> 
  </div>
<% end %>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Editar Ingrediente</h1>
<%= render 'form' %>
<%= link_to  "Inicio", root_path %>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/new.html.erb
<h1>Nuevo Ingrediente</h1>
<%= render 'form' %>
<%= link_to  "Inicio", root_path %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant Orders</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%=form_with model: @order, local: true do |form| %>
  <div class = "form-erros">
    <% if @order.errors.any? %>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div>
    <%= form.label :room %>
    <%= form.text_field :room %>
  </div>

  <div>
    <%= form.label :table %>
    <%= form.text_field :table %>
  </div>

  <div>
    <%= form.label :dish_id %>
    <%= form.collection_select :dish_id, Dish.all, :id, :name, { selected: @dish_id, include_hidden: false }, {:multiple => true} %>
  </div>

  <div>
    <%= form. submit %> 
  </div>
<% end %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Editar pedido</h1>
<%= render 'form' %>
<%= link_to  "Atras", orders_path %>

app/views/orders/index.html.erb
<h1>Pedido</h1>
<%= link_to  "Nuevo pedido", new_order_path %>
<%= link_to  "Atras", root_path %>
<% @orders.each do |order| %>
<p>Pedido: <%= link_to  order.room, order_path(order) %></p>
<p>Mesa: <%= order.table %></p>
<%= link_to  "Editar", edit_order_path(order) %>
<%= link_to "Borrar", order_path(order), method: :delete, data:{confirm:"Are you sure?"}%>
<% end %>

app/views/orders/new.html.erb
<h1>Nuevo pedido</h1>
<%= render 'form' %>
<%= link_to  "Atras", orders_path %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>